 <nav>
      <ul>
        <li>
          <a href="index.php" aria-current="page">Home</a>
        </li>
        <li>
          <a href="jobs.php">Jobs</a>
        </li>
        <li>
          <a href="apply.php">Apply</a>
        </li>
        <li>
          <a href="about.php">About us</a>
        </li>
        <li>
          <a href="mailto:info@smarttech.com.au">Contact</a>
        </li>
        <li>
          <a href="user_logout.php">LogOut</a>
        </li>
      </ul>
    </nav>